package io.github.danadep.vibecoded;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks code that was generated by AI tools.
 * 
 * <p>Use this annotation to indicate code created with AI assistance
 * and whether it has been verified by a human developer.</p>
 * 
 * @since 1.0.0
 */
@Documented
@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface VibeCoded {

    /**
     * The AI tool used to generate the code (e.g.: ChatGPT, Claude, GitHub Copilot, etc.).
     *
     * @return the name of the AI tool, or empty string if not specified
     */
    String tool() default "";

    /**
     * Whether this code has been verified by a human developer.
     *
     * @return true if human verified, false otherwise
     */
    boolean humanVerified() default false;
}
